export enum SocketTopics {
  FRONTEND_LISTENER_TOPIC = "FRONTEND_LISTENER_TOPIC",
  FRONTEND_EMITTER_TOPIC = "FRONTEND_EMITTER_TOPIC",
  DEVTOOLS_CLIENT_EMITTER_TOPIC = "DEVTOOLS_CLIENT_EMITTER_TOPIC",
}
