export enum SocketTopics {
  DEVTOOLS_APP_MAIN_LISTENER = "DEVTOOLS_APP_MAIN_LISTENER",
  DEVTOOLS_APP_MAIN_EMITTER = "DEVTOOLS_APP_MAIN_EMITTER",
  DEVTOOLS_APP_CLIENT_LISTENER = "DEVTOOLS_APP_CLIENT_LISTENER",
  DEVTOOLS_APP_CLIENT_EMITTER = "DEVTOOLS_APP_CLIENT_EMITTER",
}
