/* eslint-disable no-param-reassign */
import { app, BrowserWindow, clipboard, Data, ipcMain, nativeImage } from "electron";
import Store from "electron-store";

import { startServer } from "server";

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
// eslint-disable-next-line global-require
if (require("electron-squirrel-startup")) {
  app.quit();
}

const store = new Store();
const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 900,
    width: 1200,
    autoHideMenuBar: true,
    icon: "./src/app/assets/logo.svg",
    webPreferences: {
      nodeIntegration: true,
      enableRemoteModule: true,
      contextIsolation: false,
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  if (process.env.NODE_ENV !== "production") {
    mainWindow.webContents.openDevTools();
  }

  mainWindow.webContents.session.webRequest.onHeadersReceived((details, callback) => {
    if (details.responseHeaders) {
      details.responseHeaders["Cross-Origin-Opener-Policy"] = ["same-origin"];
      details.responseHeaders["Cross-Origin-Embedder-Policy"] = ["require-corp"];
    }
    callback({ responseHeaders: details.responseHeaders });
  });
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on("ready", createWindow);
app.whenReady().then(() => {
  ipcMain.on("electron-store-get", async (event, val) => {
    event.returnValue = store.get(val);
  });
  ipcMain.on("electron-store-set", async (_, key, val) => {
    store.set(key, val);
  });

  ipcMain.on("electron-store-delete", async (_, key) => {
    try {
      store.delete(key);
    } catch (error) {
      console.error("🚀 ~ ipcMain.on ~ error:", error);
    }
  });

  ipcMain.on("clipboard", async (_, val: Data & { img?: string }) => {
    if (val.img) {
      clipboard.writeImage(nativeImage.createFromBuffer(Buffer.from(val.img, "base64")));
    } else {
      clipboard.write(val);
    }
  });
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.

// **********
// SERVER
// **********

console.log("STARTING SERVER");
console.log("STARTING SERVER");
console.log("STARTING SERVER");
console.log("STARTING SERVER");
console.log("STARTING SERVER");
startServer();
