export enum DisplayOptions {
  name = "name",
  mainLine = "mainLine",
  badges = "badges",
  description = "description",
  admonitions = "admonitions",
  admonitionsByType = "admonitionsByType",
  import = "import",
  example = "example",
  preview = "preview",
  parameters = "parameters",
  parameter = "parameter",
  methods = "methods",
  method = "method",
  returns = "returns",
  typeReferences = "typeReferences",
  additionalLinks = "additionalLinks",
}
