export enum SocketTopics {
  APP_MAIN_LISTENER = "APP_MAIN_LISTENER",
  DEVTOOLS_APP_MAIN_EMITTER = "DEVTOOLS_APP_MAIN_EMITTER",
  APP_INSTANCE_LISTENER = "APP_INSTANCE_LISTENER",
  APP_INSTANCE_EMITTER = "APP_INSTANCE_EMITTER",
  DEVTOOLS_PLUGIN_LISTENER = "DEVTOOLS_PLUGIN_LISTENER",
}
