/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [{ type: "autogenerated", dirName: "documentation" }],
  api: [{ type: "autogenerated", dirName: "api" }],
  guides: [{ type: "autogenerated", dirName: "guides" }],
};

module.exports = sidebars;
