name: Debug Yarn Cache
on: push

jobs:
  debug_yarn_cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "yarn"
          cache-dependency-path: yarn.lock

      - name: List available caches
        run: |
          echo "Available cache keys:"
          gh cache list --limit 50
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Restore node_modules cache
        uses: actions/cache/restore@v3
        id: cache-node-modules
        with:
          path: node_modules
          key: yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-

      - name: Install dependencies if cache miss
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Create cache info
        run: |
          mkdir -p cache-info
          echo "Cache hit: ${{ steps.cache-node-modules.outputs.cache-hit }}" > cache-info/yarn-cache-info.txt
          echo "Cache key: ${{ steps.cache-node-modules.outputs.cache-primary-key }}" >> cache-info/yarn-cache-info.txt
          echo "Cache matched key: ${{ steps.cache-node-modules.outputs.cache-matched-key }}" >> cache-info/yarn-cache-info.txt
          echo "Timestamp: $(date)" >> cache-info/yarn-cache-info.txt
          echo "" >> cache-info/yarn-cache-info.txt
          echo "Yarn.lock hash: $(shasum yarn.lock)" >> cache-info/yarn-cache-info.txt
          echo "Node modules size: $(du -sh node_modules 2>/dev/null || echo 'not found')" >> cache-info/yarn-cache-info.txt

      - name: Upload cache info
        uses: actions/upload-artifact@v4
        with:
          name: yarn-cache-info-${{ github.run_number }}
          path: cache-info/
          retention-days: 7
