name: Debug Yarn Cache
on: push

jobs:
  debug_yarn_cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "yarn"
          cache-dependency-path: yarn.lock

      - name: List available caches
        run: |
          echo "Available cache keys:"
          gh cache list --limit 50
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Restore node_modules cache
        uses: actions/cache/restore@v3
        id: cache-node-modules
        with:
          path: node_modules
          key: yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-

      - name: Install dependencies if cache miss
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Create cache archive
        run: |
          mkdir -p cache-export

          # Create basic info file
          echo "Cache hit: ${{ steps.cache-node-modules.outputs.cache-hit }}" > cache-export/cache-info.txt
          echo "Cache key: ${{ steps.cache-node-modules.outputs.cache-primary-key }}" >> cache-export/cache-info.txt
          echo "Cache matched key: ${{ steps.cache-node-modules.outputs.cache-matched-key }}" >> cache-export/cache-info.txt
          echo "Timestamp: $(date)" >> cache-export/cache-info.txt
          echo "Yarn.lock hash: $(shasum yarn.lock)" >> cache-export/cache-info.txt
          echo "Node modules size: $(du -sh node_modules 2>/dev/null || echo 'not found')" >> cache-export/cache-info.txt

          # Create node_modules archive
          if [ -d "node_modules" ]; then
            echo "Creating node_modules archive..."
            tar -czf cache-export/node_modules.tar.gz node_modules/
            echo "Archive created: $(ls -lh cache-export/node_modules.tar.gz)"
          else
            echo "node_modules directory not found" > cache-export/no-node-modules.txt
          fi

      - name: Upload cached node_modules
        uses: actions/upload-artifact@v4
        with:
          name: cached-node-modules-${{ github.run_number }}
          path: cache-export/
          retention-days: 7
