name: Release packages

on:
  push:
    branches:
      - beta
      - alpha

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - run: yarn install
      - run: yarn build
      - run: yarn lint
      - run: yarn test
      - run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.PROD_GITHUB_SECRET }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
