name: Release packages

on:
  push:
    branches:
      - main
      - beta
      - alpha

defaults:
  run:
    shell: sh

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Wait on tests
        uses: lewagon/wait-on-check-action@v1.1.2
        with:
          ref: ${{ github.ref }}
          check-name: "Run tests"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - uses: actions/checkout@main

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Get Yarn cache
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Run Cache
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install packages
        run: yarn --prefer-offline

      - name: Build
        run: yarn build

      - name: Publish
        run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.PROD_GITHUB_SECRET }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
