name: Tests

on: push

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    container: "node:14-alpine"
    steps:
      - uses: actions/checkout@v2
      - run: yarn bootstrap
      - run: yarn build
      - run: yarn lint
      - run: yarn test
