name: Tests

on: push

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    container: "node:14-alpine"
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn build
      - uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: c206a2ed5aa86c7480a13634e91e440a27a98a5d134653f8ea9a7d5f987e68c3
        with:
          coverageCommand: yarn test --coverage
          coverageLocations: |
            ${{github.workspace}}/packages/core/coverage/lcov.info:lcov
            ${{github.workspace}}/packages/react/coverage/lcov.info:lcov
